### ISSUE TITLE
"{} Message" when opening K-mer list

### ISSUE THREAD

**Issue by jakewendt** [RitchieLabIGH/iMOKA#14]
Claudio,

I just had a successful run on a dataset that produced large aggregated k-mer lists with k=51 (~800MB) and k=31 (1GB).

When I attempt to load it into the GUI, the little modal window simply shows "{}    Message" and it doesn't load. The file does not appear to be corrupted. I will attempt to rerun.

<img width="517" alt="Screen Shot 2021-07-22 at 2 58 37 PM" src="https://user-images.githubusercontent.com/43850/126714912-9a9142a4-1c04-48b8-bc57-0f13c6361db4.png">

The random forest output file loads nicely.

Are there limitations on the size of file the GUI can handle? Is there another reason that this might occur?

Thanks
Jake

**Comment by jakewendt** [comment]
Rerunning the aggregation step resulted in an identical file.

**Comment by CloXD** [comment]
Hello Jake,
yes, probably the file is too big to be opened by the CLI. If you want to send me one of them I can try to fix the problem or find a workaround. In the meanwhile, increasing the accuracy threshold (-t) of the aggregation step you can reduce the total number of k-mers and the file should be smaller. 
Another suggestion when you have so many results is to filter the k-mers, using the GUI or the way it's more convenient for you, before running the random forest to remove, for example, k-mers with low expression (in the cli you can remove k-mers that have a raw count equal to a given threshold in at least one sample) or select only k-mer labelled with events to your choice. 
I won't be able to work on it till next week, but thank you again for your feedback.
Cheers
Claudio

**Comment by jakewendt** [comment]
Thank you. I will certainly try your suggestion. We had some bad storms here in Tucson on Thursday night and I just now gained full internet access.

I just shared a folder with you on box that contains a large K-mer list file and output.

**Comment by jakewendt** [comment]
Setting `--origin-threshold` to 90, up from the default of 80, dropped the K-mer list file to about 25% of the size and it loaded fine.

**Comment by RitchieLabIGH** [comment]
Hello, 
thank you for your patience. It's actually a known Node issue ( it cannot create such a long string and store it in memory ).
```
Error: Cannot create a string longer than 0x1fffffe8 characters
    at Object.slice (buffer.js:606:37)
    at Buffer.toString (buffer.js:803:14)
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:58:23) {
  code: 'ERR_STRING_TOO_LONG'
}
```
I'll have to think to a method to reduce the file dimension in case of a high number of k-mers, divide the output in multiple JSON or something similar. For now, the best solution is to work with the k-mer list given in tsv format and if you need the GUI, increase the --origin-threshold and work with a smaller subset.
Thank you again for your feedback. 
Cheers,
Claudio

**Comment by jakewendt** [comment]
Thank you Claudio. 

Do we know exactly what the size limitation is?

**Comment by jakewendt** [comment]
Looks like it is ~256MB.
