### ISSUE TITLE
the singularity image

### ISSUE THREAD

**Issue by yizhouc** [RitchieLabIGH/iMOKA#18]
Hello Geno,
I am interested in iMoka and could not find the singularity image for the link. What is the name tag for the imalge?
thanks Yizhou

**Comment by RitchieLabIGH** [comment]
Dear Yizhou,
thank you for your interest in iMOKA. You can find the releases of iMOKA ( singularity image and GUI installation packages ) at this page: https://github.com/RitchieLabIGH/iMOKA/releases under the "Assets" sections.
The version 1.0 is the one used for the publication, the v1.1 is the one in development with few bug fixes, improvements of the algorithm and annotation of the repetitive elements ( by default it's present the annotation of the human hg38 reference ).
Best regards,
Claudio

**Comment by yizhouc** [comment]
Dear Claudio,
Thank you for the quick reply.  I download the iMOKA core. It works. 
Regards
Yizhou
