### ISSUE TITLE
How to incorporate paired end reads?

### ISSUE THREAD

**Issue by archiesachdeva** [RitchieLabIGH/iMOKA#4]
Hi, 

I have forward and reverse reads for each sample in fastq.gz format. I would like to know how to create the source.tsv file for the first step?
Does iMOKA take two fastq files as input (as follows)? OR should I merge the forward and reverse reads in one fastq file? 

sample_1_name	sample_1_group	sample_1_forward_read_file     sample_1_reverseComplement_read_file
sample_2_name	sample_2_group	sample_2_forward_read_file     sample_2_reverseComplement_read_file

This is a great software for k-mer based analysis. But I am stuck on the issue to incorporate paired end read files. 
Looking forward to your suggestion.

-Archie

**Comment by CloXD** [comment]
Hello,
to incorporate paired end, just give the location of the two files in the last column. 
For example:
sample_1            responsive        ./fastq/sample_1_R1.fq.gz;./fastq/sample_1_R2.fq.gz
sample_2            responsive        ./fastq/sample_2_R1.fq.gz;./fastq/sample_2_R2.fq.gz
If two files are given, they are automatically considered paired.
I'll add the example in the README https://github.com/RitchieLabIGH/iMOKA/tree/master/iMOKA_core
Thank you for the feedback!
Cheers,
Claudio

**Comment by CloXD** [comment]
I just noticed a bug in case of paired end whose name doesn't end with *1.* or *2.* 
Now is fixed, I committed the change and uploaded the docker and singularity images. 
Sorry for the inconvenient.
Cheers,
Claudio
