### ISSUE TITLE
cant get singularity to run

### ISSUE THREAD

**Issue by philt31** [RitchieLabIGH/iMOKA#7]
iMOKA wont run on my mac. I've tried running it on ubuntu on a virtual machine but when i give it the singularity address eg:
https://github.com/RitchieLabIGH/iMOKA/releases/download/v1.0/iMOKA
or my local address I get the error:

Options given are empty
check options
/bin/sh: 1: singularity: not found
"Command failed: singularity --version\n/bin/sh 1: singularity: not found\n"
COMPLETED

any ideas?

**Comment by CloXD** [comment]
Hello,
iMOKA_core requires singularity to run. You can install it following those instructions: https://sylabs.io/guides/3.7/user-guide/quick_start.html 
Despite there are some ports of singularity on mac and windows, the linux version is more stable and documented.
The iMOKA GUI works on windows and mac mainly to display pre-computed results or to run the processes on a cluster.
I'll keep the issue open if you need more information or meet other problems.
Cheers,
Claudio
